### ISSUE TITLE
lobbyTime broken w/ pvpConfig.yml

### ISSUE THREAD

**Issue by YepImRobbie** [MineSworn/UltimateArena#129] opened 2015-10-23 00:11 UTC
# Main Configuration for the PvP Arena Type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 240
lobbyTime: 10
maxDeaths: 5
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: false
cashReward: 0
rewards:
killStreaks:
  60:
    - item,heyhacker,46,1

Lobby time is always 85 regardless of changing it.

**Comment by YepImRobbie** [comment] 2015-10-23 00:20
I think defaultClass is also still not working, I have spaces in the kit's name, that might be why? I put defaultClass: 'LEVEL 01 KIT' in the nuketown.dat file.

**Comment by YepImRobbie** [comment] 2015-10-23 00:20
Arena time integer is not being recognised either

**Comment by YepImRobbie** [comment] 2015-10-23 00:25
Blank message shown if concluded message is removed

**Comment by YepImRobbie** [comment] 2015-10-23 00:27
Blank message shown for join arena please wait message if removed

**Comment by YepImRobbie** [comment] 2015-10-23 00:29
No way to get rid of null team won the match at map message

**Comment by YepImRobbie** [comment] 2015-10-23 00:43
Looks like killStreaks stopped working too, I'm getting strength potions again.

**Comment by dmulloy2** [comment] 2015-10-24 00:58
Can't reproduce any of the configuration stuff, seems to be working fine.

**Comment by YepImRobbie** [comment] 2015-10-25 19:27
Ok, using the latest jar I deleted UA's folder, and regenerated it. Configs do not generate, and that would seem to explain as of why killStreaks, gameTime and lobbyTime integers were not being read?

**Comment by dmulloy2** [comment] 2015-10-25 21:07
Type configs are located at /UltimateArena/types/<type>/config.yml. I guess I forgot to delete the old ones, but that should be fixed as of the latest commit.

**Comment by YepImRobbie** [comment] 2015-10-27 03:41
permissionNode: ''

Is wiped from the class files, unless you changed how permission nodes are stated.

**Comment by dmulloy2** [comment] 2015-10-27 20:56
Specifying permission nodes was always a bit clunky and didn't always work, so I replaced it with ````needsPermission: true/false````. The format for permission nodes is ````ultimatearena.class.[class name lower case]````.

**Comment by YepImRobbie** [comment] 2015-10-28 00:53
Dan, if a class has spaces in the name is it recognised as an underscore?

**Closed** 2015-10-28 02:30 UTC
