### ISSUE TITLE
Constant teleporting

### ISSUE THREAD

**Issue by Neylion** [MineSworn/UltimateArena#152] opened 2016-05-14 12:27 UTC
Hello!

In search of a pvp plugin I stumbled across your dev builds and tried it out today. I managed to set up the arena and everything (FFA type), but when players join the arena they constantly teleport to the lobby point (in a glitchy way), which makes it impossible to do anything since the teleporting cancels chat etc. 

If you wait out the timer so the arena actually start the players teleport back and forth between the different arena spawns as if they instantly die and respawn at a spawn location.

The only way to get out of this loop is to quit the game.

**Comment by dmulloy2** [comment] 2016-06-01 01:08
The plugin strictly enforces the arena and lobby boundaries, so if players leave the area you defined, they get teleported back.

**Comment by RAZERMC** [comment] 2016-06-27 21:02
i experience this on spleef setup
the problem is the regioning system is not clear. 
when i set the first point via /ua sp it will not ask for the second point but will ask for the lobby point
thus the confusion on setting the region points. 

Note when you are setting points look at the block you are standing on to set the point there.

**Comment by dmulloy2** [comment] 2016-08-14 03:06
Selection is done based on WorldEdit selections, not points.

**Comment by RAZERMC** [comment] 2016-08-23 21:14
ow now i get it i thought i was supposed to stand on a block then do /ua sp 
So as I understand this Im supposed to select a region then do /us sp?

**Comment by RAZERMC** [comment] 2016-08-23 21:15
This might also solve my problem with the TDM lobby which prevent my players to move

**Comment by dmulloy2** [comment] 2016-08-24 16:11
I should probably make this clearer in the instructions. Let me know if using the regions fixes the issue for you.

**Comment by dmulloy2** [comment] 2016-08-27 20:37
Fixed in https://github.com/MineSworn/UltimateArena/commit/e26d556e40a224f1301d3c31f1f18a3afefe2c9d

**Closed by dmulloy2** 2016-08-27 20:37 UTC
Labels: Bug
