### ISSUE TITLE
Many many issues... Please help 12 server network in need of this plugin!

### ISSUE THREAD

**Issue by Zilacon** [MineSworn/UltimateArena#100] opened 2015-03-05 23:14 UTC
Alright so for the longest time my network has TRIED to get your plugin to work. Because its 1 plugin for almost every mini game and it supported signs to join and all of that it was a no brainer to go with this.

I run Modded MC Servers 1.2.5/1.5.2/1.6.4 and i have tried all of your bukkit releases for those specific mc versions. They all dont work! They will start up but once you go to setup an arena everything was wrong. Like once someone won a spleef game you were stuck there, the game never ended, and you couldn't get out or even do /ua leave to get out. I had to disconnect and reconnect from the server just to leave a game that i won.

So i downloaded your latest version i think its made for 1.7.10? Like many of my plugins that are made for 1.7.10 they are cross-compatible with 1.6.4. It starts up fine on all of my servers but 1.2.5 but i wasn't expecting it to go that far back in compatibility anyways.

But now whenever we setup an arena it makes human meteors, when someone joins a spleef arena they are spawned 100 blocks in the air and they fall to their death.

Any help on this matter would be greatly appreciated because the only other way we could get mini games working is to download 15 separate plugins and configure all of them... I would rather just stick with UA.

**Comment by Petpeeve** [comment] 2015-03-05 23:34
I concur with this statement. I am a fellow admin working alongside Zilacon to get our arenas up and running. I have spent the last two days staying up late trying to sort out the issues and hopefully find a fix myself but it simply isn't working as intended. I can understand a few bugs here and there being it's a completely different version, but as stated above, players are spawned many blocks above the set points, that was my main concern. Some more concerns are the fact that the process of creating the arenas themselves seem to be very bugged and not fully functional. When creating a KOTH arena it skips over the "add a flag" step and jumps straight to setting player positions, but while setting player positions it claims to be on the "add a flag" step at the same time. It's quite hard to explain. 

I really like the concept of your plugin and I would love to get it working on our network, as many players have been requesting mini games for quite some time and this is the only plugin we found to suit our community. Hopefully you can get back to us with useful information on how to get it running smoothly on 1.6.4. Minecraft.

Warm Regards,
Blake

**Comment by dmulloy2** [comment] 2015-03-06 00:51
What version are you using?

**Comment by Zilacon** [comment] 2015-03-06 00:51
Latest build from your jenkins.

**Comment by dmulloy2** [comment] 2015-03-06 01:23
I'll look into this tomorrow when I don't have school

**Comment by Jawakotb** [comment] 2015-03-06 02:18
Thank you dan!

**Comment by Petpeeve** [comment] 2015-03-06 03:22
Thank you so much, looking forward to a fix of some kind! =)

**Comment by dmulloy2** [comment] 2015-03-07 01:35
Should be fixed in the latest build.

**Comment by Petpeeve** [comment] 2015-03-07 21:44
Good morning! We put the latest build on our server to try it out and see if the issues were resolved, and while the 'spawning above the arena in spleef' issue has been resolved, there are still many problems related to spleef and others that I'm sure could be a simple fix. When starting the arena, you can choose ANY class, from archer to hunter to sniper, etc. There is also a spleef option but I don't trust the players to respect the game and choose spleef, they'd much rather choose archer and win from across the map. Next, we have the advanced genetics mod on our server so any time anyone with genetics falls in to the lava, they won't take any lava damage. I'm wondering if you can make it possible for players to be eliminated as soon as they touch lava, or perhaps disable all buffs when entering an arena? The last problem with spleef was the name it's given when it's started. I think it's a simple colour bug but when creating an arena it prompts players to input /ua join spleefwhite instead of /ua join spleef. I think that may be related to 1.7 or 1.8 colors that don't work in 1.6.4. http://prntscr.com/6dzf8l That's a screenshot of the problem.

So as to not bombard you with issues, I will only add king of the hill on to this and perhaps later on I can list a few more issues or if you're comfortable I can edit on more issues as you are able to solve them. These all seem like simple fixes. In King of the Hill, the steps are still very very off putting and misleading, as displayed in this screenshot. http://prntscr.com/6dzm1z It seems to be confusing itself thinking I'm placing flags all over the place when I'm trying to set player spawns? And I'm only trying to set 4 player spawns and it seems to think the flag itself is also a player spawn. We didn't have enough testers online this morning to test it out but I'm thinking if 5 people join that one player will automatically get a lead because they spawn at the flag. During the arena, no players can do damage to any other players in King of the Hill. Completely confused by this. Lastly the result of the king of the hill arena makes the ground and air a bit cluttered with random objects, I don't know if these serve a purpose. http://prntscr.com/6dzl8g

Thank you for all your help, we still have many tiny issues with the rest of the arenas that will more than likely need to be buffed out (which we can save for after you manage to look in to the two arenas we've been testing most) but we couldn't be more thankful for your dedication to your users, even the ones that are behind a few versions!

We'll be regularly checking this issue to see if anything has been fixed or if you need more information we will gladly give it to you!

**Comment by dmulloy2** [comment] 2015-03-07 23:53
Random white insertions were fixed in this commit: https://github.com/dmulloy2/SwornAPI/commit/54f81246e803e5cbf40b3a66da213c3ad8af80e4

Go ahead and report the rest of the issues.

**Comment by Petpeeve** [comment] 2015-03-08 00:04
Alright, give me just a moment and I'll compile a bullet-point style list with problems under each arena! Thanks so much again! You're very fast with the fixes! I'll have the list within a half hour to an hour!

**Comment by Petpeeve** [comment] 2015-03-09 02:25
So sorry for the late response, it was a lot more in depth than I imagined it would be. So below is a list of bugs that we've found so far to be the most affecting. They aren't too serious but Spleef is the buggiest one so far.

KOTH
------
* No rewards

Spleef
------
* Lets you choose any class (Archer, Sniper, Brute, etc) You should only have a shovel. People choose archer and snipe from across the spleef arena haha.
* Multiple Lives (There should only be one death and then elimination)

FFA
------
* Class Selection Menu closes randomly at times.
* Invisible players at random times (Possible bug)

Mob Arena
------
* Class Selection Menu closes randomly at times.
* No rewards

CTF
------
* No rewards

Infect
------
* Doesn't tell you when you become infected so it makes it very confusing.

Conquest
------
* Can not be created. "Arena Type Conquest does not exist!"

Hunger Games, Bomb and PvP seem to work fine.

Added note, when entering an arena type, if you accidentally enter a space before the arena type, it somehow errors with Computer Craft, I think Zilacon would be able to provide logs if you needed them, but I assume you are a Vanilla person so it isn't too much of a big deal.

Thank you so much for your work so far! Hopefully if you can find some solutions to these bugs we will be good to go!

**Comment by Zilacon** [comment] 2015-03-09 02:30
Here is the logs for the CC error and the error if you leave a space after a arena name in the command:

3-08 18:18:04 [INFO] [UltimateArena] Successfully deleted arena: infect!
03-08 18:18:12 [INFO] [Minecraft] computercraft: Error running task.
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.shared.peripheral.monitor.TileMonitor.addComputer(TileMonitor.java:841)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.shared.peripheral.monitor.MonitorPeripheral.attach(MonitorPeripheral.java:190)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.attach(PeripheralAPI.java:79)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.apis.PeripheralAPI.startup(PeripheralAPI.java:332)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.computer.Computer.initLua(Computer.java:587)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.computer.Computer.access$1100(Computer.java:26)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.computer.Computer$1.execute(Computer.java:694)
03-08 18:18:12 [SEVERE] [Minecraft]  at dan200.computercraft.core.computer.ComputerThread$1$1.run(ComputerThread.java:115)
03-08 18:18:12 [SEVERE] [Minecraft]  at java.lang.Thread.run(Thread.java:745)
03-08 18:18:24 [WARNING] [UltimateArena] Encountered an exception while executing command create: java.lang.IllegalArgumentException: Name cannot be empty!
Affected classes:
  org.apache.commons.lang.Validate.notEmpty(Line 321) [Validate.class]
  net.dmulloy2.ultimatearena.api.ArenaTypeHandler.getArenaType(Line 48) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.UltimateArena.createArena(Line 1004) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.commands.CmdCreate.perform(Line 28) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.commands.Command.execute(Line 126) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.handlers.CommandHandler.onCommand(Line 167) [UltimateArena.jar]
  org.bukkit.command.PluginCommand.execute(Line 44) [PluginCommand.class]
  org.bukkit.command.SimpleCommandMap.dispatch(Line 192) [SimpleCommandMap.class]
  org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(Line 533) [CraftServer.class]

**Comment by Zilacon** [comment] 2015-03-13 15:22
Any update on this?

**Comment by dmulloy2** [comment] 2015-03-13 20:54
Sorry for the late response, been busy with school and whatnot.

Thanks for the list.  Looking over it, it seems to me that most of the issues you're having are configuration-related.
* Class selection: There's a configuration option called ````whitelistedClasses```` that allows you to specify which classes a player can choose from in a given arena or arena type.  In the case of spleef, you should add your spleef class to that.
* Deaths: you should set ````maxDeaths: 1```` in order for players to be kicked after their first death.
* Rewards: make sure rewards are enabled and the reward list isn't empty

As for the others:
* Conquest is called 'cq' in the plugin's internals, so you would use ````/ua create [name] cq````
* I can't vouch for infect not notifying players, last I checked it worked fine
* Invisible players and disappearing menus aren't really within UA's control.

**Comment by Petpeeve** [comment] 2015-03-14 20:07
Thank you for the response. I am working with the plugin to fix these small little things, I imagine they're mainly just personal preference fixes that we will have to do ourselves. But as of now all the game breaking bugs have been fixed so thank you so much for all of your work! If we have any problems in the future we'll be sure to create a new ticket and get in touch with you.

Best Regards,
Blake

**Comment by dmulloy2** [comment] 2015-03-14 21:40
Glad I could help!

**Closed by dmulloy2** 2015-03-14 21:40 UTC
Labels: Bug
